name: Python CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12' # Assurez-vous que cela correspond à la version de Python que vous utilisez.
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Run tests
      run: |
        pytest tests/
        # Les tests échoueront ici si pytest retourne un code d'état différent de zéro.

  create-pull-request:
    runs-on: ubuntu-latest
    needs: test # Cette job ne s'exécutera que si la job 'test' a réussi.
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v2
    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "master" # Assurez-vous que cela correspond à la branche que vous souhaitez fusionner.
        github_token: ${{ secrets.TOKEN }}
        pr_title: "Test PR"
